import { MqttMessage } from '../../../domain';

/**
 * Mock MQTT messages that would generate the current device scenario
 * These messages simulate the sequence of events that would create the devices in mockDevices.ts
 * 
 * Note: Sensor-related warnings (elevated heart rate, temperature, temperature difference) 
 * are generated by the application logic, not sent via MQTT. Only specific alerts like 
 * 0 BPM death detection and device timeouts come through MQTT alert messages.
 */

// Helper function to create MQTT messages with timestamps
const createMessage = (topic: string, payload: string, timestampOffset: number = 0): MqttMessage => ({
  topic,
  payload,
  ts: Date.now() - timestampOffset,
});

export const MOCK_MQTT_MESSAGES: MqttMessage[] = [
  // Central unit connection message - happens first
  createMessage('central', 'CU connected and ready', 15 * 60 * 1000), // 15 minutes ago

  // Most link messages happen at the beginning (15-12 minutes ago)
  // Device 2 - Cow Alpha (OK status)
  createMessage('livestock/2/link', 'Device linked with ID: 2, Time slot: 0, Period: 5000ms', 14 * 60 * 1000), // 14 minutes ago
  createMessage('livestock/2/data', '-32945000|-60650000|38.2|22.5|72', 5 * 60 * 1000), // 5 minutes ago

  // Device 3 - Cow Beta (WARN - Elevated heart rate will be generated by app logic)
  createMessage('livestock/3/link', 'Device linked with ID: 3, Time slot: 1250, Period: 5000ms', 13 * 60 * 1000), // 13 minutes ago
  createMessage('livestock/3/data', '-32935000|-60660000|39.8|25.1|85', 2 * 60 * 1000), // 2 minutes ago

  // Device 4 - Cow Gamma (ALERT - Device timeout)
  createMessage('livestock/4/link', 'Device linked with ID: 4, Time slot: 2500, Period: 5000ms', 12 * 60 * 1000), // 12 minutes ago
  createMessage('livestock/4/data', '-32960000|-60660000|38.2|25.1|72', 1 * 60 * 1000), // 1 minute ago
  createMessage('livestock/4/alert', 'ALERT: Device timeout - LSU 4 has not communicated for 10 seconds', 1 * 60 * 1000), // 1 minute ago

  // Device 5 - Cow Delta (OK status)
  createMessage('livestock/5/link', 'Device linked with ID: 5, Time slot: 3750, Period: 5000ms', 11 * 60 * 1000), // 11 minutes ago
  createMessage('livestock/5/data', '-32950000|-60640000|37.8|20.1|68', 10 * 60 * 1000), // 10 minutes ago

  // Device 6 - Cow Epsilon (WARN - Elevated heart rate will be generated by app logic)
  createMessage('livestock/6/link', 'Device linked with ID: 6, Time slot: 500, Period: 5000ms', 10 * 60 * 1000), // 10 minutes ago
  createMessage('livestock/6/data', '-32940000|-60650000|40.1|30.5|95', 30 * 1000), // 30 seconds ago

  // Device 7 - Cow Zeta (WARN - Temperature equal to ambient will be generated by app logic)
  createMessage('livestock/7/link', 'Device linked with ID: 7, Time slot: 1750, Period: 5000ms', 9 * 60 * 1000), // 9 minutes ago
  createMessage('livestock/7/data', '-32955000|-60650000|38.5|38.5|75', 3 * 60 * 1000), // 3 minutes ago

  // Device 8 - Cow Eta (ALERT - 0 BPM, deceased)
  createMessage('livestock/8/link', 'Device linked with ID: 8, Time slot: 3000, Period: 5000ms', 8 * 60 * 1000), // 8 minutes ago
  createMessage('livestock/8/data', '-32965000|-60640000|39.5|26.2|0', 45 * 1000), // 45 seconds ago

  // Device 9 - Cow Theta (OK status)
  createMessage('livestock/9/link', 'Device linked with ID: 9, Time slot: 4250, Period: 5000ms', 7 * 60 * 1000), // 7 minutes ago
  createMessage('livestock/9/data', '-32940000|-60650000|38.0|21.3|70', 7 * 60 * 1000), // 7 minutes ago

  // Device 10 - Cow Iota (ALERT - Device timeout) - linked later
  createMessage('livestock/10/link', 'Device linked with ID: 10, Time slot: 1000, Period: 5000ms', 6 * 60 * 1000), // 6 minutes ago
  createMessage('livestock/10/data', '-32950000|-60650000|37.5|20.0|65', 5 * 60 * 1000), // 5 minutes ago
  createMessage('livestock/10/alert', 'ALERT: Device timeout - LSU 10 has not communicated for 10 seconds', 1 * 60 * 1000), // 1 minute ago
];

/**
 * Additional MQTT messages for testing different scenarios
 */
export const ADDITIONAL_MQTT_MESSAGES: MqttMessage[] = [
  // Test temperature difference warning
  createMessage('livestock/10/link', 'Device linked with ID: 10, Time slot: 2000, Period: 5000ms', 1 * 60 * 1000),
  createMessage('livestock/10/data', '-32950000|-60650000|25.0|24.0|65', 1 * 60 * 1000), // Very small temp difference

  // Test multiple alerts
  createMessage('livestock/11/link', 'Device linked with ID: 11, Time slot: 3500, Period: 5000ms', 2 * 60 * 1000),
  createMessage('livestock/11/data', '-32940000|-60650000|42.0|20.0|150', 2 * 60 * 1000), // High temp + high heart rate
  createMessage('livestock/11/alert', 'ALERT: Device timeout - LSU 11 has not communicated for 10 seconds', 2 * 60 * 1000),

  // Test JSON alert format
  createMessage('livestock/12/link', 'Device linked with ID: 12, Time slot: 750, Period: 5000ms', 30 * 1000),
  createMessage('livestock/12/data', '-32930000|-60650000|39.0|22.0|80', 30 * 1000),
  createMessage('livestock/12/alert', 'ALERT: Device timeout - LSU 12 has not communicated for 10 seconds', 30 * 1000),
];
